// Real Travel Dataset with Live Destination URLs & English / Arabic Content

export const POPULAR_DESTINATIONS = [
  {"id": "paris", "nameEn": "Paris", "nameAr": "باريس", "countryEn": "France", "countryAr": "فرنسا", "code": "PAR", "lat": 48.8566, "lng": 2.3522, "descEn": "The City of Light", "descAr": "مدينة النور", "image": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80"},
  {"id": "tokyo", "nameEn": "Tokyo", "nameAr": "طوكيو", "countryEn": "Japan", "countryAr": "اليابان", "code": "TYO", "lat": 35.6762, "lng": 139.6503, "descEn": "Where tradition meets innovation", "descAr": "حيث يلتقي التقليد بالابتكار", "image": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80"},
  {"id": "bali", "nameEn": "Bali", "nameAr": "بالي", "countryEn": "Indonesia", "countryAr": "إندونيسيا", "code": "DPS", "lat": -8.4095, "lng": 115.1889, "descEn": "Island of the Gods", "descAr": "جزيرة الآلهة", "image": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80"},
  {"id": "new-york", "nameEn": "New York", "nameAr": "نيويورك", "countryEn": "United States", "countryAr": "الولايات المتحدة", "code": "NYC", "lat": 40.7128, "lng": -74.0060, "descEn": "The city that never sleeps", "descAr": "المدينة التي لا تنام", "image": "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80"},
  {"id": "santorini", "nameEn": "Santorini", "nameAr": "سانتوريني", "countryEn": "Greece", "countryAr": "اليونان", "code": "JTR", "lat": 36.3932, "lng": 25.4615, "descEn": "Aegean caldera views", "descAr": "إطلالات بحر إيجة الساحرة", "image": "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80"},
  {"id": "london", "nameEn": "London", "nameAr": "لندن", "countryEn": "United Kingdom", "countryAr": "المملكة المتحدة", "code": "LON", "lat": 51.5074, "lng": -0.1278, "descEn": "Historic royal elegance", "descAr": "الأناقة الملكية التاريخية", "image": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80"},
  {"id": "dubai", "nameEn": "Dubai", "nameAr": "دبي", "countryEn": "UAE", "countryAr": "الإمارات العربية المتحدة", "code": "DXB", "lat": 25.2048, "lng": 55.2708, "descEn": "Luxury skyscraper oasis", "descAr": "واحة ناطحات السحاب الفاخرة", "image": "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80"},
  {"id": "miami", "nameEn": "Miami", "nameAr": "ميامي", "countryEn": "United States", "countryAr": "الولايات المتحدة", "code": "MIA", "lat": 25.7617, "lng": -80.1918, "descEn": "Art Deco beachfront glamour", "descAr": "سحر شواطئ الآرت ديكو", "image": "https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=800&q=80"},
  {"id": "rome", "nameEn": "Rome", "nameAr": "روما", "countryEn": "Italy", "countryAr": "إيطاليا", "code": "ROM", "lat": 41.9028, "lng": 12.4964, "descEn": "The Eternal City", "descAr": "المدينة الخالدة", "image": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80"},
  {"id": "barcelona", "nameEn": "Barcelona", "nameAr": "برشلونة", "countryEn": "Spain", "countryAr": "إسبانيا", "code": "BCN", "lat": 41.3851, "lng": 2.1734, "descEn": "Gaudí architecture & Mediterranean sea", "descAr": "عمارة غودي وبحر المتوسط", "image": "https://images.unsplash.com/photo-1583422409516-1500d4df0081?auto=format&fit=crop&w=800&q=80"}
];

export const DESTINATION_GUIDES = [
  {"id": "paris", "tipsEn": ["Book Louvre tickets in advance", "Learn basic French phrases", "Use the Metro"], "tipsAr": ["احجز تذاكر اللوفر مسبقًا", "تعلم عبارات فرنسية أساسية", "استخدم المترو"], "bestTimeEn": "Spring (April-June) or Fall (Sept-Oct)", "bestTimeAr": "الربيع (أبريل-يونيو) أو الخريف (سبتمبر-أكتوبر)", "topAttractionsEn": ["Eiffel Tower", "Louvre Museum", "Notre-Dame"], "topAttractionsAr": ["برج إيفل", "متحف اللوفر", "نوتردام"], "avgRates": "$150 - $400"},
  {"id": "tokyo", "tipsEn": ["Get a Suica card", "No tipping required", "Use Google Maps for transit"], "tipsAr": ["احصل على بطاقة سويكا", "لا يلزم البقشيش", "استخدم خرائط جوجل للتنقل"], "bestTimeEn": "Spring for cherry blossoms (March-April)", "bestTimeAr": "الربيع لأزهار الكرز (مارس-أبريل)", "topAttractionsEn": ["Senso-ji", "Shibuya Crossing", "Tokyo Tower"], "topAttractionsAr": ["سينسوجي", "تقاطع شيبويا", "برج طوكيو"], "avgRates": "$100 - $350"},
  {"id": "bali", "tipsEn": ["Rent a scooter", "Drink bottled water", "Respect local customs"], "tipsAr": ["استأجر سكوتر", "اشرب مياه معبأة", "احترم العادات المحلية"], "bestTimeEn": "Dry season (April-October)", "bestTimeAr": "موسم الجفاف (أبريل-أكتوبر)", "topAttractionsEn": ["Uluwatu Temple", "Ubud Monkey Forest", "Tegallalang Rice Terrace"], "topAttractionsAr": ["معبد أولوواتو", "غابة القرود في أوبود", "مدرجات أرز تيجالالانج"], "avgRates": "$50 - $200"},
  {"id": "new-york", "tipsEn": ["Walk fast", "Get a MetroCard", "Visit parks in morning"], "tipsAr": ["امش بسرعة", "احصل على بطاقة مترو", "قم بزيارة الحدائق في الصباح"], "bestTimeEn": "Fall (Sept-Nov) or Spring (April-June)", "bestTimeAr": "الخريف (سبتمبر-نوفمبر) أو الربيع (أبريل-يونيو)", "topAttractionsEn": ["Central Park", "Times Square", "Statue of Liberty"], "topAttractionsAr": ["سنترال بارك", "تايمز سكوير", "تمثال الحرية"], "avgRates": "$200 - $500"},
  {"id": "santorini", "tipsEn": ["Wear comfortable shoes", "Book sunset dinners early", "Rent an ATV"], "tipsAr": ["ارتدِ أحذية مريحة", "احجز عشاء الغروب مبكرًا", "استأجر دباب"], "bestTimeEn": "Shoulder season (May or September)", "bestTimeAr": "الموسم المتوسط (مايو أو سبتمبر)", "topAttractionsEn": ["Oia Sunset", "Red Beach", "Akrotiri"], "topAttractionsAr": ["غروب الشمس في أويا", "الشاطئ الأحمر", "أكروتيري"], "avgRates": "$250 - $800"},
  {"id": "london", "tipsEn": ["Stand on the right on escalators", "Get an Oyster card", "Pack an umbrella"], "tipsAr": ["قف على اليمين في السلالم المتحركة", "احصل على بطاقة أويستر", "احزم مظلة"], "bestTimeEn": "Summer (June-August) for best weather", "bestTimeAr": "الصيف (يونيو-أغسطس) لأفضل طقس", "topAttractionsEn": ["Tower of London", "British Museum", "London Eye"], "topAttractionsAr": ["برج لندن", "المتحف البريطاني", "عين لندن"], "avgRates": "$180 - $450"},
  {"id": "dubai", "tipsEn": ["Dress modestly", "Use taxis or Metro", "Avoid summer heat"], "tipsAr": ["ارتد ملابس محتشمة", "استخدم سيارات الأجرة أو المترو", "تجنب حرارة الصيف"], "bestTimeEn": "Winter (November-March)", "bestTimeAr": "الشتاء (نوفمبر-مارس)", "topAttractionsEn": ["Burj Khalifa", "Dubai Mall", "Palm Jumeirah"], "topAttractionsAr": ["برج خليفة", "دبي مول", "نخلة جميرا"], "avgRates": "$150 - $600"},
  {"id": "miami", "tipsEn": ["Sunscreen is a must", "Rent a car for day trips", "Learn some Spanish"], "tipsAr": ["واقي الشمس ضروري", "استأجر سيارة للرحلات اليومية", "تعلم بعض الإسبانية"], "bestTimeEn": "Spring (March-May)", "bestTimeAr": "الربيع (مارس-مايو)", "topAttractionsEn": ["South Beach", "Art Deco District", "Little Havana"], "topAttractionsAr": ["الشاطئ الجنوبي", "منطقة آرت ديكو", "هافانا الصغيرة"], "avgRates": "$180 - $500"},
  {"id": "rome", "tipsEn": ["Carry cash for small cafes", "Watch out for pickpockets", "Wear comfortable shoes"], "tipsAr": ["احمل نقوداً للمقاهي الصغيرة", "احذر من النشالين", "ارتد أحذية مريحة"], "bestTimeEn": "Spring (April-May) or Fall (Sept-Oct)", "bestTimeAr": "الربيع (أبريل-مايو) أو الخريف (سبتمبر-أكتوبر)", "topAttractionsEn": ["Colosseum", "Vatican City", "Trevi Fountain"], "topAttractionsAr": ["الكولوسيوم", "مدينة الفاتيكان", "نافورة تريفي"], "avgRates": "$120 - $350"},
  {"id": "barcelona", "tipsEn": ["Book Sagrada Familia early", "Eat dinner late", "Keep belongings secure"], "tipsAr": ["احجز ساجرادا فاميليا مبكرًا", "تناول العشاء متأخرًا", "حافظ على أمان ممتلكاتك"], "bestTimeEn": "Early Summer (May-June) or Fall (Sept-Oct)", "bestTimeAr": "أوائل الصيف (مايو-يونيو) أو الخريف (سبتمبر-أكتوبر)", "topAttractionsEn": ["Sagrada Familia", "Park Güell", "Gothic Quarter"], "topAttractionsAr": ["ساجرادا فاميليا", "بارك غويل", "الحي القوطي"], "avgRates": "$130 - $400"}
];

export const HOTELS_DATA = [
  {"id": "h1", "category": "hotels", "titleEn": "Le Grand Plaza Resort & Spa", "titleAr": "منتجع وسبا لوجراند بلازا", "locationEn": "Paris", "locationAr": "باريس", "addressEn": "12 Avenue Montaigne, 8th arr., Paris", "addressAr": "12 شارع مونتين، الدائرة الثامنة، باريس", "price": 340, "originalPrice": 420, "rating": 4.9, "reviewsCount": 1280, "stars": 5, "lat": 48.8661, "lng": 2.3048, "provider": "Booking.com", "directUrl": "https://www.booking.com/searchresults.html?ss=Paris", "image": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Free WiFi", "Swimming Pool", "Spa & Wellness", "Eiffel View", "Breakfast Included"], "amenitiesAr": ["واي فاي مجاني", "مسبح", "سبا وعافية", "إطلالة على إيفل", "إفطار مشمول"]},
  {"id": "h2", "category": "hotels", "titleEn": "The Tokyo Skytree Boutique Hotel", "titleAr": "فندق طوكيو سكاي تري البوتيكي", "locationEn": "Tokyo", "locationAr": "طوكيو", "addressEn": "Oshiage, Sumida-ku, Tokyo", "addressAr": "أوشياجي، سوميدا-كو، طوكيو", "price": 215, "originalPrice": 260, "rating": 4.8, "reviewsCount": 940, "stars": 4, "lat": 35.7101, "lng": 139.8107, "provider": "Agoda", "directUrl": "https://www.agoda.com/search?city=5085", "image": "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Free WiFi", "City Skyline View", "Onsen Hot Spring", "24/7 Concierge", "Metro Access"], "amenitiesAr": ["واي فاي مجاني", "إطلالة على أفق المدينة", "ينابيع حارة", "بواب 24/7", "دخول المترو"]},
  {"id": "h3", "category": "hotels", "titleEn": "Ubud Cliffside Wellness Sanctuary", "titleAr": "ملاذ أوبود كليفسيد الصحي", "locationEn": "Bali", "locationAr": "بالي", "addressEn": "Jalan Raya Kedewatan, Ubud, Bali", "addressAr": "جالان رايا كيدواتان، أوبود، بالي", "price": 180, "originalPrice": 240, "rating": 4.95, "reviewsCount": 730, "stars": 5, "lat": -8.5069, "lng": 115.2625, "provider": "Booking.com", "directUrl": "https://www.booking.com/searchresults.html?ss=Ubud", "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Infinity Pool", "Jungle View", "Organic Restaurant", "Free Yoga", "Spa"], "amenitiesAr": ["مسبح لا متناهي", "إطلالة على الغابة", "مطعم عضوي", "يوغا مجانية", "سبا"]},
  {"id": "h4", "category": "hotels", "titleEn": "Manhattan Sky Suites & Penthouse", "titleAr": "أجنحة وبنتهاوس مانهاتن سكاي", "locationEn": "New York", "locationAr": "نيويورك", "addressEn": "5th Avenue & 55th St, Midtown, New York", "addressAr": "الجادة الخامسة والشارع 55، وسط المدينة، نيويورك", "price": 495, "originalPrice": 580, "rating": 4.7, "reviewsCount": 2100, "stars": 5, "lat": 40.7615, "lng": -73.9754, "provider": "Booking.com", "directUrl": "https://www.booking.com/searchresults.html?ss=New+York", "image": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Central Park View", "Rooftop Lounge", "Fitness Center", "Pet Friendly", "Valet Parking"], "amenitiesAr": ["إطلالة على سنترال بارك", "صالة على السطح", "مركز لياقة بدنية", "صديق للحيوانات الأليفة", "خدمة صف السيارات"]},
  {"id": "h5", "category": "hotels", "titleEn": "Santorini Sunset Caldera Suites", "titleAr": "أجنحة سانتوريني صن ست كالديرا", "locationEn": "Santorini", "locationAr": "سانتوريني", "addressEn": "Oia Village, Santorini", "addressAr": "قرية أويا، سانتوريني", "price": 390, "originalPrice": 480, "rating": 4.92, "reviewsCount": 880, "stars": 5, "lat": 36.4618, "lng": 25.3753, "provider": "Agoda", "directUrl": "https://www.agoda.com/search?city=18330", "image": "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Cave Pool", "Sea View", "Private Terrace", "Champagne Breakfast", "Free Airport Shuttle"], "amenitiesAr": ["مسبح الكهف", "إطلالة على البحر", "شرفة خاصة", "إفطار بالشمبانيا", "نقل مجاني للمطار"]},
  {"id": "h6", "category": "hotels", "titleEn": "London Thameside Luxury Inn", "titleAr": "نزل لندن الفاخر على نهر التايمز", "locationEn": "London", "locationAr": "لندن", "addressEn": "South Bank, London", "addressAr": "الضفة الجنوبية، لندن", "price": 320, "originalPrice": 400, "rating": 4.85, "reviewsCount": 1120, "stars": 5, "lat": 51.5055, "lng": -0.1147, "provider": "Booking.com", "directUrl": "https://www.booking.com/searchresults.html?ss=London", "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["River View", "Spa", "Fine Dining", "Free WiFi", "Concierge"], "amenitiesAr": ["إطلالة على النهر", "سبا", "طعام فاخر", "واي فاي مجاني", "بواب"]},
  {"id": "h7", "category": "hotels", "titleEn": "Burj Al Arab Jumeirah", "titleAr": "برج العرب جميرا", "locationEn": "Dubai", "locationAr": "دبي", "addressEn": "Jumeirah St, Dubai", "addressAr": "شارع جميرا، دبي", "price": 1200, "originalPrice": 1500, "rating": 4.95, "reviewsCount": 3500, "stars": 7, "lat": 25.1412, "lng": 55.1852, "provider": "Agoda", "directUrl": "https://www.agoda.com/search?city=14552", "image": "https://images.unsplash.com/photo-1546412414-e1885259563a?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Butler Service", "Private Beach", "Helipad", "Luxury Spa", "Michelin Dining"], "amenitiesAr": ["خدمة الخادم الشخصي", "شاطئ خاص", "مهبط طائرات", "سبا فاخر", "طعام ميشلان"]},
  {"id": "h8", "category": "hotels", "titleEn": "Miami Beach Oceanfront Resort", "titleAr": "منتجع ميامي بيتش على المحيط", "locationEn": "Miami", "locationAr": "ميامي", "addressEn": "Collins Ave, Miami Beach, FL", "addressAr": "شارع كولينز، ميامي بيتش، فلوريدا", "price": 280, "originalPrice": 350, "rating": 4.7, "reviewsCount": 1500, "stars": 4, "lat": 25.7907, "lng": -80.1300, "provider": "Booking.com", "directUrl": "https://www.booking.com/searchresults.html?ss=Miami", "image": "https://images.unsplash.com/photo-1535827841776-24afc1e255ac?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Private Beach Access", "Pool Cabanas", "Fitness Center", "Valet", "Nightclub"], "amenitiesAr": ["دخول شاطئ خاص", "كبائن المسبح", "مركز لياقة", "خدمة صف السيارات", "نادي ليلي"]},
  {"id": "h9", "category": "hotels", "titleEn": "Hotel Artemide Rome", "titleAr": "فندق أرتيميد روما", "locationEn": "Rome", "locationAr": "روما", "addressEn": "Via Nazionale, Rome", "addressAr": "فيا نازيونالي، روما", "price": 190, "originalPrice": 230, "rating": 4.8, "reviewsCount": 2100, "stars": 4, "lat": 41.8998, "lng": 12.4925, "provider": "Agoda", "directUrl": "https://www.agoda.com/search?city=10219", "image": "https://images.unsplash.com/photo-1551882547-ff40c0d129df?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Rooftop Terrace", "Spa", "Free Minibar", "Airport Transfer", "City View"], "amenitiesAr": ["تراس على السطح", "سبا", "ميني بار مجاني", "نقل المطار", "إطلالة على المدينة"]},
  {"id": "h10", "category": "hotels", "titleEn": "W Barcelona", "titleAr": "دبليو برشلونة", "locationEn": "Barcelona", "locationAr": "برشلونة", "addressEn": "Plaça de la Rosa dels Vents, Barcelona", "addressAr": "ساحة روزا ديلز فينتس، برشلونة", "price": 380, "originalPrice": 450, "rating": 4.85, "reviewsCount": 3200, "stars": 5, "lat": 41.3684, "lng": 2.1904, "provider": "Booking.com", "directUrl": "https://www.booking.com/searchresults.html?ss=Barcelona", "image": "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Infinity Pool", "Beachfront", "Michelin Restaurant", "Spa", "Rooftop Bar"], "amenitiesAr": ["مسبح لا متناهي", "مواجه للشاطئ", "مطعم ميشلان", "سبا", "بار على السطح"]}
];

export const VACATION_RENTALS_DATA = [
  {"id": "v1", "category": "rentals", "titleEn": "Cliffside Glass Villa with Heated Infinity Pool", "titleAr": "فيلا زجاجية على الجرف مع مسبح لا متناهي مدفأ", "locationEn": "Bali", "locationAr": "بالي", "addressEn": "Uluwatu Cliffs, Bali", "addressAr": "منحدرات أولوواتو، بالي", "price": 290, "originalPrice": 350, "rating": 4.96, "reviewsCount": 142, "bedrooms": 3, "bathrooms": 3, "maxGuests": 6, "propertyType": "Villa", "lat": -8.8149, "lng": 115.0884, "provider": "VRBO", "directUrl": "https://www.vrbo.com/search?q=Bali", "image": "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Oceanfront Pool", "Chef Kitchen", "Superhost Status", "Air Conditioning", "High-Speed Starlink"], "amenitiesAr": ["مسبح على واجهة المحيط", "مطبخ الشيف", "حالة المضيف المتميز", "تكييف هواء", "إنترنت سريع"]},
  {"id": "v2", "category": "rentals", "titleEn": "Historical Haussmann Loft with Eiffel Balcony", "titleAr": "دور علوي تاريخي من هوسمان مع شرفة إيفل", "locationEn": "Paris", "locationAr": "باريس", "addressEn": "Le Marais / 7th Arrondissement, Paris", "addressAr": "لو ماريه / الدائرة السابعة، باريس", "price": 240, "originalPrice": 290, "rating": 4.9, "reviewsCount": 215, "bedrooms": 2, "bathrooms": 2, "maxGuests": 4, "propertyType": "Apartment", "lat": 48.8570, "lng": 2.3580, "provider": "VRBO", "directUrl": "https://www.vrbo.com/search?q=Paris", "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Eiffel Tower View", "Elevator", "Espresso Bar", "Washer/Dryer", "Wine Cellar"], "amenitiesAr": ["إطلالة على برج إيفل", "مصعد", "بار إسبرسو", "غسالة/مجفف", "قبو نبيذ"]},
  {"id": "v3", "category": "rentals", "titleEn": "Kyoto Machiya Traditional Garden Townhouse", "titleAr": "تاون هاوس بحديقة تقليدية في كيوتو ماتشيا", "locationEn": "Tokyo", "locationAr": "طوكيو", "addressEn": "Gion District, Kyoto / Tokyo Connect", "addressAr": "منطقة جيون، كيوتو", "price": 310, "originalPrice": 380, "rating": 4.98, "reviewsCount": 98, "bedrooms": 3, "bathrooms": 2, "maxGuests": 6, "propertyType": "House", "lat": 35.0037, "lng": 135.7772, "provider": "VRBO", "directUrl": "https://www.vrbo.com/search?q=Kyoto", "image": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Private Zen Garden", "Cedar Ofuro Tub", "Tatami Rooms", "Matcha Tea Set", "Bicycles Provided"], "amenitiesAr": ["حديقة زن خاصة", "حوض استحمام من خشب الأرز", "غرف التاتامي", "مجموعة شاي ماتشا", "توفير دراجات"]},
  {"id": "v4", "category": "rentals", "titleEn": "SoHo Designer Duplex Penthouse", "titleAr": "بنتهاوس دوبلكس مصمم في سوهو", "locationEn": "New York", "locationAr": "نيويورك", "addressEn": "Spring St & West Broadway, SoHo, NY", "addressAr": "شارع سبرينغ وبرودواي الغربي، سوهو، نيويورك", "price": 580, "originalPrice": 690, "rating": 4.88, "reviewsCount": 176, "bedrooms": 3, "bathrooms": 3.5, "maxGuests": 6, "propertyType": "Penthouse", "lat": 40.7248, "lng": -74.0018, "provider": "VRBO", "directUrl": "https://www.vrbo.com/search?q=New+York", "image": "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=1000&q=80", "amenitiesEn": ["Private Rooftop Terrace", "Cast Iron Windows", "Sonos Sound", "Keyed Elevator", "Fireplace"], "amenitiesAr": ["تراس خاص على السطح", "نوافذ من الحديد الزهر", "صوت سونوس", "مصعد بمفتاح", "مدفأة"]}
];

export const CAR_RENTALS_DATA = [
  {"id": "c1", "category": "cars", "titleEn": "Tesla Model Y Long Range Electric", "titleAr": "تسلا موديل واي كهربائية طويلة المدى", "locationEn": "Paris", "locationAr": "باريس", "carTypeEn": "Electric / SUV", "carTypeAr": "كهربائية / دفع رباعي", "passengers": 5, "bags": 3, "transmissionEn": "Automatic", "transmissionAr": "أوتوماتيك", "price": 78, "originalPrice": 95, "dailyRate": 78, "originalRate": 95, "rating": 4.9, "lat": 49.0097, "lng": 2.5479, "provider": "DiscoverCars", "supplier": "Sixt", "directUrl": "https://www.discovercars.com/car-rental/search?pick_up=Paris", "image": "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1000&q=80", "featuresEn": ["Free Autopilot", "Supercharger Access", "Unlimited Mileage", "Collision Damage Waiver"], "featuresAr": ["القيادة الذاتية المجانية", "دخول شاحن فائق", "أميال غير محدودة", "إعفاء من أضرار التصادم"]},
  {"id": "c2", "category": "cars", "titleEn": "BMW 4 Series Convertible", "titleAr": "بي إم دبليو الفئة الرابعة كابريوليه", "locationEn": "Santorini", "locationAr": "سانتوريني", "carTypeEn": "Convertible / Luxury", "carTypeAr": "كابريوليه / فاخرة", "passengers": 4, "bags": 2, "transmissionEn": "Automatic", "transmissionAr": "أوتوماتيك", "price": 110, "originalPrice": 140, "dailyRate": 110, "originalRate": 140, "rating": 4.95, "lat": 36.3932, "lng": 25.4615, "provider": "DiscoverCars", "supplier": "Hertz", "directUrl": "https://www.discovercars.com/car-rental/search?pick_up=Santorini", "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=80", "featuresEn": ["Soft Top Roof", "Leather Seats", "GPS Navigation", "Full Insurance Included"], "featuresAr": ["سقف علوي ناعم", "مقاعد جلدية", "ملاحة GPS", "تأمين كامل مشمول"]},
  {"id": "c3", "category": "cars", "titleEn": "Range Rover Sport HSE Luxury SUV", "titleAr": "رينج روفر سبورت HSE دفع رباعي فاخرة", "locationEn": "London", "locationAr": "لندن", "carTypeEn": "SUV / Luxury", "carTypeAr": "دفع رباعي / فاخرة", "passengers": 5, "bags": 4, "transmissionEn": "Automatic", "transmissionAr": "أوتوماتيك", "price": 135, "originalPrice": 170, "dailyRate": 135, "originalRate": 170, "rating": 4.85, "lat": 51.4700, "lng": -0.4543, "provider": "DiscoverCars", "supplier": "Avis", "directUrl": "https://www.discovercars.com/car-rental/search?pick_up=London", "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1000&q=80", "featuresEn": ["All-Wheel Drive", "Panoramic Sunroof", "Unlimited Mileage", "24/7 Roadside Assistance"], "featuresAr": ["دفع رباعي", "فتحة سقف بانورامية", "أميال غير محدودة", "مساعدة على الطريق 24/7"]}
];
